export const searchOptions = [
  {key: "Android", value: "Android", text: "Android"},
  {key: "Art", value: "Art", text: "Art"},
  {key: "Artificial Intelligence", value: "Artificial Intelligence", text: "Artificial Intelligence"},
  {key: "Astronomy", value: "Astronomy", text: "Astronomy"},
  {key: "Austen", value: "Austen", text: "Austen"},
  {key: "Baseball", value: "Baseball", text: "Baseball"},
  {key: "Basketball", value: "Basketball", text: "Basketball"},
  {key: "Bhagat", value: "Bhagat", text: "Bhagat"},
  {key: "Biography", value: "Biography", text: "Biography"},
  {key: "Brief", value: "Brief", text: "Brief"},
  {key: "Business", value: "Business", text: "Business"},
  {key: "Camus", value: "Camus", text: "Camus"},
  {key: "Cervantes", value: "Cervantes", text: "Cervantes"},
  {key: "Christie", value: "Christie", text: "Christie"},
  {key: "Classics", value: "Classics", text: "Classics"},
  {key: "Comics", value: "Comics", text: "Comics"},
  {key: "Cook", value: "Cook", text: "Cook"},
  {key: "Cricket", value: "Cricket", text: "Cricket"},
  {key: "Cycling", value: "Cycling", text: "Cycling"},
  {key: "Desai", value: "Desai", text: "Desai"},
  {key: "Design", value: "Design", text: "Design"},
  {key: "Development", value: "Development", text: "Development"},
  {key: "Digital Marketing", value: "Digital Marketing", text: "Digital Marketing"},
  {key: "Drama", value: "Drama", text: "Drama"},
  {key: "Drawing", value: "Drawing", text: "Drawing"},
  {key: "Dumas", value: "Dumas", text: "Dumas"},
  {key: "Education", value: "Education", text: "Education"},
  {key: "Everything", value: "Everything", text: "Everything"},
  {key: "Fantasy", value: "Fantasy", text: "Fantasy"},
  {key: "Film", value: "Film", text: "Film"},
  {key: "Finance", value: "Finance", text: "Finance"},
  {key: "First", value: "First", text: "First"},
  {key: "Fitness", value: "Fitness", text: "Fitness"},
  {key: "Football", value: "Football", text: "Football"},
  {key: "Future", value: "Future", text: "Future"},
  {key: "Games", value: "Games", text: "Games"},
  {key: "Gandhi", value: "Gandhi", text: "Gandhi"},
  {key: "Homer", value: "Homer", text: "Homer"},
  {key: "Horror", value: "Horror", text: "Horror"},
  {key: "Hugo", value: "Hugo", text: "Hugo"},
  {key: "Ibsen", value: "Ibsen", text: "Ibsen"},
  {key: "Journey", value: "Journey", text: "Journey"},
  {key: "Kafka", value: "Kafka", text: "Kafka"},
  {key: "King", value: "King", text: "King"},
  {key: "Lahiri", value: "Lahiri", text: "Lahiri"},
  {key: "Larsson", value: "Larsson", text: "Larsson"},
  {key: "Learn", value: "Learn", text: "Learn"},
  {key: "Literary Fiction", value: "Literary Fiction", text: "Literary Fiction"},
  {key: "Make", value: "Make", text: "Make"},
  {key: "Manage", value: "Manage", text: "Manage"},
  {key: "Marquez", value: "Marquez", text: "Marquez"},
  {key: "Money", value: "Money", text: "Money"},
  {key: "Mystery", value: "Mystery", text: "Mystery"},
  {key: "Negotiate", value: "Negotiate", text: "Negotiate"},
  {key: "Painting", value: "Painting", text: "Painting"},
  {key: "Philosophy", value: "Philosophy", text: "Philosophy"},
  {key: "Photography", value: "Photography", text: "Photography"},
  {key: "Poetry", value: "Poetry", text: "Poetry"},
  {key: "Production", value: "Production", text: "Production"},
  {key: "Programming", value: "Programming", text: "Programming"},
  {key: "React", value: "React", text: "React"},
  {key: "Redux", value: "Redux", text: "Redux"},
  {key: "River", value: "River", text: "River"},
  {key: "Robotics", value: "Robotics", text: "Robotics"},
  {key: "Rowling", value: "Rowling", text: "Rowling"},
  {key: "Satire", value: "Satire", text: "Satire"},
  {key: "Science Fiction", value: "Science Fiction", text: "Science Fiction"},
  {key: "Shakespeare", value: "Shakespeare", text: "Shakespeare"},
  {key: "Singh", value: "Singh", text: "Singh"},
  {key: "Swimming", value: "Swimming", text: "Swimming"},
  {key: "Tale", value: "Tale", text: "Tale"},
  {key: "Thrun", value: "Thrun", text: "Thrun"},
  {key: "Time", value: "Time", text: "Time"},
  {key: "Tolstoy", value: "Tolstoy", text: "Tolstoy"},
  {key: "Travel", value: "Travel", text: "Travel"},
  {key: "Ultimate", value: "Ultimate", text: "Ultimate"},
  {key: "Virtual Reality", value: "Virtual Reality", text: "Virtual Reality"},
  {key: "Web Development", value: "Web Development", text: "Web Development"},
  {key: "iOS", value: "iOS", text: "iOS"},
]
